#
# Makefile for misc devices that really don't fit anywhere else.
#
obj-y += oradt_hd720_dsi_cmd.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
